In [1]:
import numpy as np
from sklearn.datasets import load_boston
boston = load_boston()

x_data = boston.data
y_data = boston.target
print(type(x_data))
print(x_data.shape)
print(y_data.shape)


<class 'numpy.ndarray'>
(506, 13)
(506,)


In [30]:
'''
def hypothesis(theta,x):
    m = x.shape[0]
    sum = theta[0]
    for i in range(1,m+1):
        sum += theta[i]*x[i-1]
    return sum

def gradient(X,Y,theta):
    m = X.shape[0]
    n = X.shape[1]
    grad = np.zeros((n+1))
    for i in range(m):
        grad[0] += (hypothesis(theta,X[i])-Y[i])
        for j in range(1,n+1):
            grad[j] += (hypothesis(theta,X[i])-Y[i])*X[i][j-1]
    return grad
def gradient_decent(X,Y,learning_rate = 0.001,max_itr = 10):
    n = X.shape[1]
    theta = np.zeros((n+1))
    for i in range(max_itr):
        grad = gradient(X,Y,theta)
        for j in range(n+1):
            theta[j] = theta[j] - learning_rate*grad[j]
    return theta
theta = gradient_decent(x_data,y_data)
print(theta)
'''

[-6.61190572e+47 -2.96295358e+48 -6.59333342e+48 -7.99061580e+48
 -4.52513995e+46 -3.76247031e+47 -4.12855789e+48 -4.71686787e+49
 -2.36825344e+48 -7.31035340e+48 -2.91646992e+50 -1.23353592e+49
 -2.35648248e+50 -8.81562824e+48]


# Using Sklearn Library


In [42]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
reg = LinearRegression(normalize = True)
x_train,x_test,y_train,y_test = train_test_split(x_data,y_data,test_size = 0.2)
reg.fit(x_train,y_train)
print(reg.coef_)
print(reg.intercept_)

[-9.53028948e-02  4.82340987e-02  4.92786381e-02  1.52134444e+00
 -1.93926114e+01  3.40735087e+00  1.31093154e-02 -1.38400155e+00
  3.14324720e-01 -1.36806984e-02 -1.03900877e+00  9.73932687e-03
 -5.39957606e-01]
40.52509171556808


# Accuracy of Regression

In [56]:
print(reg.score(x_train,y_train))


0.7501895104057386


In [59]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(reg,x_train,y_train,cv = 10,scoring = 'r2')
print(scores)
print(scores.mean())

[0.64780638 0.74919196 0.49672239 0.81431421 0.68568273 0.84508302
 0.67460803 0.55305733 0.73887806 0.82901531]
0.7034359413526332


In [83]:
l1 = np.zeros((4,2))
l2 = np.zeros((4,1))+1
print(l1)
print(l2)
print()
l3 = np.concatenate((l2,l1),axis = 1)
print(l3)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1.]
 [1.]
 [1.]
 [1.]]

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
